package com.postechfiap_group130.techchallenge_fastfood.api.data.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.postechfiap_group130.techchallenge_fastfood.core.entities.PaymentStatusEnum;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "payment")
public class PaymentDynamoDBEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    
    @DynamoDBAttribute(attributeName = "orderId")
    private Long orderId;
    
    @DynamoDBAttribute(attributeName = "amount")
    private BigDecimal amount;
    
    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "status")
    private PaymentStatusEnum status;
    
    public PaymentDynamoDBEntity(Long orderId, BigDecimal amount) {
        this.orderId = orderId;
        this.amount = amount;
        this.status = PaymentStatusEnum.PENDING;
    }
}
